version: '3.7'

services:
  bot:
    container_name: bw-manager-bot
    build: .
    command: python3 main.py
    restart: always
    volumes:
      - .:/app
    networks:
      - botnet

  redis:
    container_name: bw-manager-redis
    image: redis:alpine
    networks:
      - botnet
    ports:
      - "6379:6379"
    volumes:
      - bw-redis-data:/data


networks:
  botnet:
    name: bw-manager-net


volumes:
  bw-redis-data:
